image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install --upgrade pip
  - name: python-modules
    command: >
      pip install opencv-python &&
      pip install face_recognition &&
      pip install pymongo &&
      python main.py



